name: Run Hello World Test
description: "Run hello world test."

inputs:
  cookie:
    description: "Cookie for download authorization."
    required: true

runs:
  using: "composite"
  steps:
      - name: Prepare QEMU
        uses: ./.github/workflows/actions/prepare-qemu
        with:
          cookie: ${{ inputs.cookie }}

      - name: Download test "hello world"
        uses: actions/download-artifact@v4
        with:
          name: hello_world
          path: ./artifacts

      - name: Run test "hello world"
        run: qemu-system-arm -machine netduinoplus2 -nographic -semihosting-config enable=on,target=native -kernel ./artifacts/hello_world > output.txt
        shell: bash

      - name: Emit ground truth output
        run: echo "hello world!" > truth.txt
        shell: bash
      
      - name: Check test output
        run: diff output.txt truth.txt
        shell: bash
