[package]
name = "hopter"
version = "0.1.0"
edition = "2021"

[dependencies]
static_assertions = "1.1.0"
heapless = "0.8"
spin = "0.9.8"
int-enum = "1.1.1"

[dependencies.hopter_proc_macro]
git = "https://github.com/ZhiyaoMa98/hopter-procedural-macro.git"

[dependencies.cortex-m]
version = "0.7.7"
features = ["inline-asm"]

[dependencies.owning_ref]
git = "https://github.com/theseus-os/owning-ref-rs.git"

[dependencies.crossbeam]
version = "0.8.4"
default-features = false

[dependencies.gimli]
version = "0.29.0"
default-features = false
features = [ "read" ]

[dependencies.fallible-iterator]
version = "0.3"
default-features = false

[dependencies.intrusive-collections]
version = "0.9.6"
features = [ "nightly" ]
