name: Check QEMU

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare QEMU
        uses: ./.github/workflows/actions/prepare-qemu
        with:
          cookie: ${{ secrets.cookie }}

      - name: Verify QEMU
        run: qemu-system-arm --version
        shell: bash
