name: Check Rust toolchain

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Rust compiler toolchain
        uses: ./.github/workflows/actions/prepare-rust-toolchain
        with:
          cookie: ${{ secrets.cookie }}

      - name: Verify Rust compiler toolchain registration
        run: cargo +segstk-rust --version
        shell: bash
