name: Run Tests for Task

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  mailbox:
    uses: ./.github/workflows/priority.yaml
    secrets:
      cookie: ${{ secrets.cookie }}
